### ISSUE TITLE
Backend code not working with Python 3.13

### ISSUE THREAD

**Issue by MartinPyka** [OpenOrion/CQAsk#4]
With Python 3.13 I do not get it running because of errors like

  File "/usr/local/lib/python3.11/site-packages/nptyping/typing_.py", line 66, in <module>
    Bool8: TypeAlias = np.bool8

or when i fix this, I get:

    from ocp_tessellate import PartGroup
ImportError: cannot import name 'PartGroup' from 'ocp_tessellate' (/usr/local/lib/python3.11/site-packages/ocp_tessellate/__init__.py)

Can you provide dependency-versions or a Dockerfile so that the backend can be started?
